name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      # After testing I've discovered that caching the NextJs build cache
      # does not significantly speed up the build time in this monorepo setup.
      # Therefore, the NextJs cache step is commented out for now.
      # Numbers were, ~ 24s to restore it and ~ 40s to save it so close to 1m to
      # maintain the cache and the build is only taking ~ 9s.
      # - name: Restore NextJs cache
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.pnpm
      #       ${{ github.workspace }}/apps/stamina-web/.next/cache
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
      #     restore-keys: |
      #       ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      # Waiting on fix for: https://github.com/anomalyco/sst/issues/6314
      - name: Add SST's bin directory to PATH
        # Writing to $GITHUB_PATH causes GitHub Actions to prepend this directory to PATH,
        # ensuring SST's version of Pulumi is found before GitHub Actions' version
        run: echo "$HOME/.config/sst/bin" >> $GITHUB_PATH

      - name: Build and Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_SCHEMA: "stamina"
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_DISABLE_SIGN_UPS: "true"
          AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
          PRODUCTION_URL: "https://stamina.illizen.com"
        run: |
          pnpm build:packages
          pnpx sst deploy --stage prod
